use std::path::PathBuf;

use anyhow::{Context, Result};

const UNSEE_MARKER_START: &str = "# >>> unsee credential protection >>>";
const UNSEE_MARKER_END: &str = "# <<< unsee credential protection <<<";

/// Shell wrapper block for POSIX shells (bash, zsh).
/// When __UNSEE_ACTIVE is set, run the command directly to prevent double-wrapping.
fn posix_block(unsee_bin: &str) -> String {
    format!(
        r#"{start}
# Auto-generated by `unsee install`. Do not edit this block.
claude() {{
    if [ -n "$__UNSEE_ACTIVE" ] || [ ! -x "{bin}" ]; then command claude "$@"; else {bin} protect -- claude "$@"; fi
}}
codex() {{
    if [ -n "$__UNSEE_ACTIVE" ] || [ ! -x "{bin}" ]; then command codex "$@"; else {bin} protect -- codex "$@"; fi
}}
gemini() {{
    if [ -n "$__UNSEE_ACTIVE" ] || [ ! -x "{bin}" ]; then command gemini "$@"; else {bin} protect -- gemini "$@"; fi
}}
{end}"#,
        start = UNSEE_MARKER_START,
        end = UNSEE_MARKER_END,
        bin = unsee_bin,
    )
}

/// Shell wrapper block for fish shell.
/// When __UNSEE_ACTIVE is set, run the command directly to prevent double-wrapping.
fn fish_block(unsee_bin: &str) -> String {
    format!(
        r#"{start}
# Auto-generated by `unsee install`. Do not edit this block.
function claude
    if set -q __UNSEE_ACTIVE; or not test -x "{bin}"; command claude $argv; else; {bin} protect -- claude $argv; end
end
function codex
    if set -q __UNSEE_ACTIVE; or not test -x "{bin}"; command codex $argv; else; {bin} protect -- codex $argv; end
end
function gemini
    if set -q __UNSEE_ACTIVE; or not test -x "{bin}"; command gemini $argv; else; {bin} protect -- gemini $argv; end
end
{end}"#,
        start = UNSEE_MARKER_START,
        end = UNSEE_MARKER_END,
        bin = unsee_bin,
    )
}

struct ShellTarget {
    name: &'static str,
    path: PathBuf,
    block: String,
}

fn detect_shells(unsee_bin: &str) -> Vec<ShellTarget> {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
    let home = PathBuf::from(home);

    let mut targets = Vec::new();

    // zsh: ~/.zshenv (loaded for all zsh sessions, even non-interactive)
    let zshenv = home.join(".zshenv");
    if zshenv.exists() || shell_available("zsh") {
        targets.push(ShellTarget {
            name: "zsh",
            path: zshenv,
            block: posix_block(unsee_bin),
        });
    }

    // bash: ~/.bashrc (loaded for interactive sessions)
    let bashrc = home.join(".bashrc");
    if bashrc.exists() || shell_available("bash") {
        targets.push(ShellTarget {
            name: "bash",
            path: bashrc,
            block: posix_block(unsee_bin),
        });
    }

    // fish: ~/.config/fish/config.fish
    let fish_config = home.join(".config/fish/config.fish");
    if fish_config.exists() || shell_available("fish") {
        targets.push(ShellTarget {
            name: "fish",
            path: fish_config,
            block: fish_block(unsee_bin),
        });
    }

    targets
}

fn shell_available(name: &str) -> bool {
    std::process::Command::new("which")
        .arg(name)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn install_to(target: &ShellTarget) -> Result<bool> {
    let existing = if target.path.exists() {
        std::fs::read_to_string(&target.path)
            .with_context(|| format!("reading {}", target.path.display()))?
    } else {
        String::new()
    };

    if existing.contains(UNSEE_MARKER_START) {
        return Ok(false); // already installed
    }

    // Ensure parent directory exists (for fish)
    if let Some(parent) = target.path.parent() {
        if !parent.exists() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
    }

    let new_content = if existing.is_empty() {
        target.block.clone()
    } else {
        format!("{}\n\n{}", existing.trim_end(), &target.block)
    };

    std::fs::write(&target.path, &new_content)
        .with_context(|| format!("writing {}", target.path.display()))?;

    Ok(true)
}

pub fn run() -> Result<()> {
    let unsee_bin = std::env::current_exe()
        .context("resolving unsee binary path")?
        .to_string_lossy()
        .to_string();

    let targets = detect_shells(&unsee_bin);

    if targets.is_empty() {
        println!("No supported shells found (zsh, bash, fish).");
        return Ok(());
    }

    let mut installed = Vec::new();
    let mut skipped = Vec::new();

    for target in &targets {
        if install_to(target)? {
            installed.push(target.name);
        } else {
            skipped.push(target.name);
        }
    }

    for name in &installed {
        println!("Installed unsee wrappers for {}", name);
    }
    for name in &skipped {
        println!("Shield wrappers already installed for {}", name);
    }

    if !installed.is_empty() {
        println!("Restart your shell to activate.");
    }

    Ok(())
}
